### ISSUE TITLE
主进程内的配置该写在哪

### ISSUE THREAD

**Issue by HiCody** [BySlin/umi-plugin-electron-builder#1]
没有main.ts主进程文件，那主进程中的一些操作该写在哪里

**Comment by BySlin** [comment]
在src/main/main.ts

**Comment by BySlin** [comment]
执行yarn add umi-plugin-electron-builder -D 之后
执行 umi dev electron 
执行之后会把相关的文件生成出来

**Comment by HiCody** [comment]
对，我后来看到了谢谢大佬
