### ISSUE TITLE
不适配 APP_ROOT 环境变量

### ISSUE THREAD

**Issue by jctaoo** [BySlin/umi-plugin-electron-builder#12]
https://github.com/BySlin/umi-plugin-electron-builder/blob/b934e712da6e3edb3e3fb94105643e388e3f7f2b/src/index.ts#L55 
在设置了 APP_ROOT 环境变量的时候，此行代码不适用，可以使用
```javascript
join(api.cwd, 'package.json')
```

**Comment by jctaoo** [comment]
我正在尝试修复它

**Comment by jctaoo** [comment]
看上去问题仍然存在，此行代码
https://github.com/BySlin/umi-plugin-electron-builder/blob/9cce7cad453d12f9bffe1af6cb44e1adc77a9d3f/src/index.ts#L53
为什么要这么处理？

我们可以重复确认一下 api.cwd 的行为：
- 当 APP_ROOT 未设置时，它指向项目根
- 当 APP_ROOT 设置时，它指向 APP_ROOT

我是用此方法验证：
```javascript
api.logger.info(api.cwd)
```
运行命令:
```shell
cross-env UMI_UI=1 APP_ROOT=src/renderer umi dev electron
```
控制台打印
```
INFO /Users/jctaoo/private-work/line_bundle_checker/src/renderer
```
运行命令:
```shell
umi dev electron
```
控制台打印
```
INFO /Users/jctaoo/private-work/line_bundle_checker
```

Note: /Users/jctaoo/private-work/line_bundle_checker 是我的项目根

**Comment by BySlin** [comment]
看看这个是不是你想要的 https://github.com/BySlin/umi-plugin-electron-builder/tree/master/examples/main%2Brenderer

**Comment by jctaoo** [comment]
是的，现在它工作正常了吗

**Comment by BySlin** [comment]
可以正常工作了，更新版本

**Comment by BySlin** [comment]
照着示例配置即可 https://github.com/BySlin/umi-plugin-electron-builder/blob/master/examples/main%2Brenderer/src/renderer/.umirc.ts
