### ISSUE TITLE
允许 .env 读取 APP_ROOT 环境变量

### ISSUE THREAD

**Issue by arvinxx** [BySlin/umi-plugin-electron-builder#15]
issue 来源：https://github.com/BySlin/umi-plugin-electron-builder/issues/9#issuecomment-781509071

APP_ROOT 写在scripts里太啰嗦了，希望能够在 .env 里配置。（我记得 umi 是支持环境变量写在 .env 里的呀？

**Comment by BySlin** [comment]
![image](https://user-images.githubusercontent.com/16970823/108582655-9eef9e80-736f-11eb-9592-e9f2a2f35de0.png)
https://umijs.org/zh-CN/docs/env-variables

umijs限制的，插件没办法解决

**Comment by arvinxx** [comment]
这样吗…好吧
