### ISSUE TITLE
能否优化下模块的版本发布

### ISSUE THREAD

**Issue by arvinxx** [BySlin/umi-plugin-electron-builder#17]
希望该模块能够参考 Semantic Version 的方式进行语义化版本发布。

比如支持了双目录结构，应该发 1.1.0 吧？

且具有完整的更新日志、能够方便使用者知道更新了啥地方，判断是否应该升级模块。

不然会出现 #16 这样的报错，刚刚还挺一脸懵逼的。

**Comment by BySlin** [comment]
增加了更新日志 https://github.com/BySlin/umi-plugin-electron-builder/blob/master/CHANGELOG.md
