### ISSUE TITLE
main.ts没有被编译导致dev/build时失败

### ISSUE THREAD

**Issue by TIS-OMiddle** [BySlin/umi-plugin-electron-builder#19]
step：任意空目录下执行
- yarn create @umijs/umi-app
- yarn add umi-plugin-electron-builder --dev
- yarn electron:dev

命令行报错
```
ERROR in ./src/main/main.ts 8:14
  Module parse failed: Unexpected token (8:14)
  You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
  | 
  | const isDevelopment = process.env.NODE_ENV === 'development';
  > let mainWindow: BrowserWindow;
  | 
  | protocol.registerSchemesAsPrivileged([
   @ multi ./node_modules/electron-webpack/out/electron-main-hmr/main-hmr ./src/main/main.ts main[1]
```

electron弹出错误窗口：
![screenshot-20210225-200734](https://user-images.githubusercontent.com/24486385/109151431-23458580-77a5-11eb-8809-78e9388f7c6c.png)

看起来像是没有把main.ts给编译到src/.umi/main/main.js，手动编译一次复制过去后正常

**Comment by BySlin** [comment]
yarn create @umijs/umi-app
yarn
yarn add umi-plugin-electron-builder --dev
yarn electron:dev

换成这样的顺序试试

**Comment by BySlin** [comment]
插件更新到1.0.17，此问题已修复

**Comment by yqnetwork** [comment]
更新的太及时了，太棒的项目了
