### ISSUE TITLE
尝试升级 2.0 遇到报错   ReferenceError: self is not defined

### ISSUE THREAD

**Issue by arvinxx** [BySlin/umi-plugin-electron-builder#23]
![image](https://user-images.githubusercontent.com/28616219/112248382-cd270d80-8c90-11eb-9080-199664375531.png)

RT，仓库地址：https://github.com/arvinxx/umi-electron-template/tree/package/umi-plugin-electron-builder_v2

**Comment by BySlin** [comment]
esbuild和typeorm不兼容 https://github.com/evanw/esbuild/issues/257
现在2.0同时支持webpack和vite，在配置参数中切换，默认为webpack构建，vite构建速度更快但兼容性有点问题

**Comment by geekftz** [comment]
how it fixed?

**Comment by BySlin** [comment]
> how it fixed?

buildType 设置为 webpack即可，
