### ISSUE TITLE
执行umi electron init之后生成了src/main/index.ts,但是执行umi dev electron之后仍然报错找不到./index.ts。

### ISSUE THREAD

**Issue by Ha0ran2001** [BySlin/umi-plugin-electron-builder#26]
执行umi dev electron报错：
┏ Electron -------------------

  App threw an error during load

┗ ----------------------------
┏ Electron -------------------

  Error: Cannot find module './index.ts'
      at webpackMissingModule (F:\Project\Front-end\React\umi-rfid\src\.umi\electron\main.js:96:45)
      at Object.<anonymous> (F:\Project\Front-end\React\umi-rfid\src\.umi\electron\main.js:96:130)
      at __webpack_require__ (F:\Project\Front-end\React\umi-rfid\src\.umi\electron\main.js:21:30)
      at F:\Project\Front-end\React\umi-rfid\src\.umi\electron\main.js:85:18
      at Object.<anonymous> (F:\Project\Front-end\React\umi-rfid\src\.umi\electron\main.js:88:10)
      at Module._compile (internal/modules/cjs/loader.js:1078:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
      at Module.load (internal/modules/cjs/loader.js:935:32)
      at Function.f._load (electron/js2c/asar_bundle.js:5:12684)

┗ ----------------------------

执行umi build electron --win下载一直卡在下面这里：
downloading     url=https://github.com/electron/electron/releases/download/v12.0.2/electron-v12.0.2-win32-x64.zip size=83 MB parts=8
我把url贴到edge浏览器能下载，chrome不能下载，是我网络的什么原因吗?

**Comment by BySlin** [comment]
尝试一下demo https://github.com/BySlin/umi-plugin-electron-builder/tree/main/examples/demo
能否提供一下最小化demo
打包下载不了，请尝试设置electron国内镜像

**Comment by Rookie-haoran** [comment]
> 尝试一下demo https://github.com/BySlin/umi-plugin-electron-builder/tree/main/examples/demo
> 能否提供一下最小化demo
> 打包下载不了，请尝试设置electron国内镜像

https://github.com/Rookie-haoran/umi-electron这是我的原始demo, 就是还未用您的插件的情况下

**Comment by Ha0ran2001** [comment]
> 尝试一下demo https://github.com/BySlin/umi-plugin-electron-builder/tree/main/examples/demo
> 能否提供一下最小化demo
> 打包下载不了，请尝试设置electron国内镜像

https://github.com/Rookie-haoran/umi-electron  这是我的原始demo, 就是还未用您的插件的情况下，之前也全局安装过，electron国内镜像配置过，

**Comment by BySlin** [comment]
![image](https://user-images.githubusercontent.com/16970823/114275323-b9332800-9a54-11eb-8edf-14c62351f342.png)
在我这里可以正常显示，可能是路径或者网络问题，请尝试配置代理
@Rookie-haoran

**Comment by Ha0ran2001** [comment]
> ![image](https://user-images.githubusercontent.com/16970823/114275323-b9332800-9a54-11eb-8edf-14c62351f342.png)
> 在我这里可以正常显示，可能是路径或者网络问题，请尝试配置代理
> @Rookie-haoran

额，好。我找找我的问题。感谢

**Comment by Ha0ran2001** [comment]
> 尝试一下demo https://github.com/BySlin/umi-plugin-electron-builder/tree/main/examples/demo
> 能否提供一下最小化demo
> 打包下载不了，请尝试设置electron国内镜像

我发现一个问题。今天我用npm那一套下来就可以。用第二种yarn就不行。之前也是用的yarn那一套。今天突然想到用npm居然就成了，不知道这是什么原因

**Comment by BySlin** [comment]
你设置的镜像可能是用npm设置的，yarn也需要设置镜像，npm设置的镜像只对npm有效
![image](https://user-images.githubusercontent.com/16970823/114299449-dd8f1300-9aed-11eb-9b93-471ba7a07d7d.png)
![image](https://user-images.githubusercontent.com/16970823/114299461-eed81f80-9aed-11eb-9b59-3e3457f5e713.png)

**Comment by Ha0ran2001** [comment]
> 你设置的镜像可能是用npm设置的，yarn也需要设置镜像，npm设置的镜像只对npm有效
> ![image](https://user-images.githubusercontent.com/16970823/114299449-dd8f1300-9aed-11eb-9b93-471ba7a07d7d.png)
> ![image](https://user-images.githubusercontent.com/16970823/114299461-eed81f80-9aed-11eb-9b59-3e3457f5e713.png)

我的yarn也是淘宝镜像啊

**Comment by Ha0ran2001** [comment]
> 你设置的镜像可能是用npm设置的，yarn也需要设置镜像，npm设置的镜像只对npm有效
> ![image](https://user-images.githubusercontent.com/16970823/114299449-dd8f1300-9aed-11eb-9b93-471ba7a07d7d.png)
> ![image](https://user-images.githubusercontent.com/16970823/114299461-eed81f80-9aed-11eb-9b59-3e3457f5e713.png)

不过确实应该是我yarn哪里没配置好，之前也遇到过一些奇怪的问题
