### ISSUE TITLE
TypeError: Cannot read property 'join' of undefined

### ISSUE THREAD

**Issue by vip55zxc** [BySlin/umi-plugin-electron-builder#28]
┏ Electron -------------------

  (node:28291) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'join' of undefined
      at createWindow (/Users/songbaoqiang/Desktop/manage-dev/src/.umi/electron/main.js:217:37)
      at /Users/songbaoqiang/Desktop/manage-dev/src/.umi/electron/main.js:230:9
      at step (/Users/songbaoqiang/Desktop/manage-dev/src/.umi/electron/main.js:197:23)
      at Object.next (/Users/songbaoqiang/Desktop/manage-dev/src/.umi/electron/main.js:178:53)
      at /Users/songbaoqiang/Desktop/manage-dev/src/.umi/electron/main.js:172:71
      at new Promise (<anonymous>)
      at module.exports../index.ts.__awaiter (/Users/songbaoqiang/Desktop/manage-dev/src/.umi/electron/main.js:168:12)
      at App.<anonymous> (/Users/songbaoqiang/Desktop/manage-dev/src/.umi/electron/main.js:228:49)
      at App.emit (events.js:315:20)
  (Use `Electron --trace-warnings ...` to show where the warning was created)

┗ ----------------------------
┏ Electron -------------------

  (node:28291) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
  (node:28291) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

┗ ----------------------------

{
  "name": "ant-design-pro",
  "version": "4.5.0",
  "private": true,
  "description": "An out-of-box UI solution for enterprise applications",
  "scripts": {
    "analyze": "cross-env ANALYZE=1 umi build",
    "build": "umi build",
    "deploy": "npm run site && npm run gh-pages",
    "dev": "npm run start:dev",
    "fetch:blocks": "pro fetch-blocks && npm run prettier",
    "gh-pages": "gh-pages -d dist",
    "i18n-remove": "pro i18n-remove --locale=zh-CN --write",
    "postinstall": "umi g tmp",
    "lint": "umi g tmp && npm run lint:js && npm run lint:style && npm run lint:prettier",
    "lint-staged:js": "eslint --ext .js,.jsx,.ts,.tsx ",
    "lint:fix": "eslint --fix --cache --ext .js,.jsx,.ts,.tsx --format=pretty ./src && npm run lint:style",
    "lint:js": "eslint --cache --ext .js,.jsx,.ts,.tsx --format=pretty ./src",
    "lint:prettier": "prettier --check \"src/**/*\" --end-of-line auto",
    "lint:style": "stylelint --fix \"src/**/*.less\" --syntax less",
    "precommit": "lint-staged",
    "prettier": "prettier -c --write \"src/**/*\"",
    "start": "cross-env REACT_APP_ENV=mock UMI_ENV=dev umi dev ",
    "start:dev": "cross-env REACT_APP_ENV=dev MOCK=none UMI_ENV=dev umi dev",
    "start:no-mock": "cross-env MOCK=none UMI_ENV=dev umi dev",
    "start:no-ui": "cross-env UMI_UI=none UMI_ENV=dev umi dev",
    "start:pre": "cross-env REACT_APP_ENV=pre UMI_ENV=dev umi dev",
    "start:test": "cross-env REACT_APP_ENV=test MOCK=none UMI_ENV=dev umi dev",
    "pretest": "node ./tests/beforeTest",
    "test": "umi test",
    "test:all": "node ./tests/run-tests.js",
    "test:component": "umi test ./src/components",
    "tsc": "tsc --noEmit",
    "rebuild-deps": "electron-builder install-app-deps",
    "electron:init": "umi electron init",
    "electron:dev": "umi dev electron",
    "electron:build:win": "umi build electron --win",
    "electron:build:mac": "umi build electron --mac",
    "electron:build:linux": "umi build electron --linux"
  },
  "lint-staged": {
    "**/*.less": "stylelint --syntax less",
    "**/*.{js,jsx,ts,tsx}": "npm run lint-staged:js",
    "**/*.{js,jsx,tsx,ts,less,md,json}": [
      "prettier --write"
    ]
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 10"
  ],
  "dependencies": {
    "@ant-design/charts": "^1.0.21",
    "@ant-design/icons": "^4.0.0",
    "@ant-design/pro-card": "^1.11.4",
    "@ant-design/pro-descriptions": "^1.2.0",
    "@ant-design/pro-form": "^1.3.0",
    "@ant-design/pro-layout": "^6.9.0",
    "@ant-design/pro-table": "^2.17.0",
    "@types/serialport": "^8.0.1",
    "@umijs/route-utils": "^1.0.33",
    "antd": "^4.10.0",
    "braft-editor": "^2.3.9",
    "classnames": "^2.2.6",
    "decimal.js": "^10.2.1",
    "lodash": "^4.17.11",
    "moment": "^2.25.3",
    "omit.js": "^2.0.2",
    "qs": "^6.9.0",
    "react": "^17.0.0",
    "react-dev-inspector": "^1.1.1",
    "react-dom": "^17.0.0",
    "react-helmet-async": "^1.0.4",
    "serialport": "^9.0.7",
    "umi": "^3.2.14",
    "umi-request": "^1.0.8",
    "electron-updater":"^4.3.8"
  },
  "devDependencies": {
    "@ant-design/pro-cli": "^1.0.28",
    "@types/classnames": "^2.2.7",
    "@types/express": "^4.17.0",
    "@types/history": "^4.7.2",
    "@types/jest": "^26.0.0",
    "@types/lodash": "^4.14.144",
    "@types/node": "^14.6.2",
    "@types/qs": "^6.5.3",
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "@types/react-helmet": "^6.1.0",
    "@umijs/fabric": "^2.5.1",
    "@umijs/plugin-blocks": "^2.0.5",
    "@umijs/plugin-esbuild": "^1.0.1",
    "@umijs/preset-ant-design-pro": "^1.2.0",
    "@umijs/preset-react": "^1.4.8",
    "@umijs/yorkie": "^2.0.3",
    "carlo": "^0.9.46",
    "chalk": "^4.0.0",
    "cross-env": "^7.0.0",
    "cross-port-killer": "^1.1.1",
    "detect-installer": "^1.0.1",
    "electron": "^12.0.4",
    "electron-builder": "^22.10.5",
    "enzyme": "^3.11.0",
    "eslint": "^7.1.0",
    "express": "^4.17.1",
    "gh-pages": "^3.0.0",
    "jsdom-global": "^3.0.2",
    "lint-staged": "^10.0.0",
    "mockjs": "^1.0.1-beta3",
    "prettier": "^2.0.1",
    "puppeteer-core": "^7.0.1",
    "stylelint": "^13.0.0",
    "typescript": "^4.0.3",
    "umi-plugin-electron-builder": "^2.0.4"
  },
  "engines": {
    "node": ">=10.0.0"
  },
  "checkFiles": [
    "src/**/*.js*",
    "src/**/*.ts*",
    "src/**/*.less",
    "config/**/*.js*",
    "scripts/**/*.js"
  ]
}

有个报错求救

**Comment by BySlin** [comment]
你这个是通过自动生成的主进程代码运行的吗？，如果修改过主进程代码，请自行检查修改过的代码

**Comment by vip55zxc** [comment]
我按教程做的 没有改主进程代码。。

**Comment by vip55zxc** [comment]
> 你这个是通过自动生成的主进程代码运行的吗？，如果修改过主进程代码，请自行检查修改过的代码



> 你这个是通过自动生成的主进程代码运行的吗？，如果修改过主进程代码，请自行检查修改过的代码

我按教程做的没有改主进程代码。。

**Comment by vip55zxc** [comment]
> 你这个是通过自动生成的主进程代码运行的吗？，如果修改过主进程代码，请自行检查修改过的代码

import { app, BrowserWindow, protocol } from 'electron';
import createProtocol from 'umi-plugin-electron-builder/lib/createProtocol';
import path from 'path';
// import installExtension, {
//   REACT_DEVELOPER_TOOLS,
// } from 'electron-devtools-installer';

const isDevelopment = process.env.NODE_ENV === 'development';
let mainWindow: BrowserWindow;

protocol.registerSchemesAsPrivileged([
    { scheme: 'app', privileges: { secure: true, standard: true } },
]);

function createWindow() {
    mainWindow = new BrowserWindow({
        width: 800,
        height: 600,
        webPreferences: {
            contextIsolation: true,
            preload: path.join(__dirname, 'preload.js'),
        },
    });
    if (isDevelopment) {
        mainWindow.loadURL('http://localhost:8000');
    } else {
        createProtocol('app');
        mainWindow.loadURL('app://./index.html');
    }
}

app.on('ready', async () => {
    // if (isDevelopment) {
    //   await installExtension(REACT_DEVELOPER_TOOLS);
    // }
    createWindow();
});

app.on('window-all-closed', () => {
    if (process.platform !== 'darwin') {
        app.quit();
    }
});

app.on('activate', () => {
    if (mainWindow === null) {
        createWindow();
    }
});


这是我主进程的代码 ，麻烦大佬帮忙看一下 多谢哈。。

**Comment by vip55zxc** [comment]
> > 你这个是通过自动生成的主进程代码运行的吗？，如果修改过主进程代码，请自行检查修改过的代码
> 
> import { app, BrowserWindow, protocol } from 'electron';
> import createProtocol from 'umi-plugin-electron-builder/lib/createProtocol';
> import path from 'path';
> // import installExtension, {
> // REACT_DEVELOPER_TOOLS,
> // } from 'electron-devtools-installer';
> 
> const isDevelopment = process.env.NODE_ENV === 'development';
> let mainWindow: BrowserWindow;
> 
> protocol.registerSchemesAsPrivileged([
> { scheme: 'app', privileges: { secure: true, standard: true } },
> ]);
> 
> function createWindow() {
> mainWindow = new BrowserWindow({
> width: 800,
> height: 600,
> webPreferences: {
> contextIsolation: true,
> preload: path.join(__dirname, 'preload.js'),
> },
> });
> if (isDevelopment) {
> mainWindow.loadURL('http://localhost:8000');
> } else {
> createProtocol('app');
> mainWindow.loadURL('app://./index.html');
> }
> }
> 
> app.on('ready', async () => {
> // if (isDevelopment) {
> // await installExtension(REACT_DEVELOPER_TOOLS);
> // }
> createWindow();
> });
> 
> app.on('window-all-closed', () => {
> if (process.platform !== 'darwin') {
> app.quit();
> }
> });
> 
> app.on('activate', () => {
> if (mainWindow === null) {
> createWindow();
> }
> });
> 
> 这是我主进程的代码 ，麻烦大佬帮忙看一下 多谢哈。。
``import { app, BrowserWindow, protocol } from 'electron';
import createProtocol from 'umi-plugin-electron-builder/lib/createProtocol';
import path from 'path';
// import installExtension, {
//   REACT_DEVELOPER_TOOLS,
// } from 'electron-devtools-installer';

const isDevelopment = process.env.NODE_ENV === 'development';
let mainWindow: BrowserWindow;

protocol.registerSchemesAsPrivileged([
    { scheme: 'app', privileges: { secure: true, standard: true } },
]);

function createWindow() {
    mainWindow = new BrowserWindow({
        width: 800,
        height: 600,
        webPreferences: {
            contextIsolation: true,
            preload: path.join(__dirname, 'preload.js'),
        },
    });
    if (isDevelopment) {
        mainWindow.loadURL('http://localhost:8000');
    } else {
        createProtocol('app');
        mainWindow.loadURL('app://./index.html');
    }
}

app.on('ready', async () => {
    // if (isDevelopment) {
    //   await installExtension(REACT_DEVELOPER_TOOLS);
    // }
    createWindow();
});

app.on('window-all-closed', () => {
    if (process.platform !== 'darwin') {
        app.quit();
    }
});

app.on('activate', () => {
    if (mainWindow === null) {
        createWindow();
    }
});
`import { app, BrowserWindow, protocol } from 'electron';
import createProtocol from 'umi-plugin-electron-builder/lib/createProtocol';
import path from 'path';
// import installExtension, {
//   REACT_DEVELOPER_TOOLS,
// } from 'electron-devtools-installer';

const isDevelopment = process.env.NODE_ENV === 'development';
let mainWindow: BrowserWindow;

protocol.registerSchemesAsPrivileged([
    { scheme: 'app', privileges: { secure: true, standard: true } },
]);

function createWindow() {
    mainWindow = new BrowserWindow({
        width: 800,
        height: 600,
        webPreferences: {
            contextIsolation: true,
            preload: path.join(__dirname, 'preload.js'),
        },
    });
    if (isDevelopment) {
        mainWindow.loadURL('http://localhost:8000');
    } else {
        createProtocol('app');
        mainWindow.loadURL('app://./index.html');
    }
}

app.on('ready', async () => {
    // if (isDevelopment) {
    //   await installExtension(REACT_DEVELOPER_TOOLS);
    // }
    createWindow();
});

app.on('window-all-closed', () => {
    if (process.platform !== 'darwin') {
        app.quit();
    }
});

app.on('activate', () => {
    if (mainWindow === null) {
        createWindow();
    }
});
`

**Comment by BySlin** [comment]
尝试一下demo能否启动 https://github.com/BySlin/umi-plugin-electron-builder/tree/main/examples/demo
