### ISSUE TITLE
请问在双目录(main+renderer)情况下，如何统一环境变量？

### ISSUE THREAD

**Issue by hemengke1997** [BySlin/umi-plugin-electron-builder#29]
如题，主进程中通过process.env获取环境变量，渲染进程中通过umi的define配置获取。
请问有什么统一的方法来获取环境变量吗？

**Comment by BySlin** [comment]
![image](https://user-images.githubusercontent.com/16970823/115841073-fe8d2780-a44e-11eb-933c-b59b1390fb9a.png)
这样

**Comment by hemengke1997** [comment]
感谢作者
