### ISSUE TITLE
2.0 运行时，修改 main 端代码，将会自动结束进程

### ISSUE THREAD

**Issue by arvinxx** [BySlin/umi-plugin-electron-builder#30]
用 example 中 `main+renderer` 案例试了下，当开启`electron:dev` ，然后修改 main 端任何代码后，会直接自动结束进程。这导致开发时每次都需要重开一遍 dev。

**Comment by arvinxx** [comment]
另外 demo 配置项有点问题，提 PR 了  #31

**Comment by BySlin** [comment]
https://github.com/BySlin/umi-plugin-electron-builder/blob/d7539092f437321e3ad1c0ae08b2022c8ef47e56/src/compile/index.ts#L92-L124
在windows下是正常的，我手上没有mac，可能是这一段路径比较不正确


https://github.com/BySlin/umi-plugin-electron-builder/blob/d7539092f437321e3ad1c0ae08b2022c8ef47e56/src/index.ts#L75-L76

alias是默认配置的，我这边在windows下也是正常的

**Comment by BySlin** [comment]
此问题已修复
