### ISSUE TITLE
请问主进程只能是在TypeScript下运行吗？

### ISSUE THREAD

**Issue by yangjiaqiao** [BySlin/umi-plugin-electron-builder#32]
把main.ts，修改为js运行报错
![image](https://user-images.githubusercontent.com/51978469/116822885-f00fe000-abb3-11eb-9a32-d3b740ec10e0.png)

**Comment by BySlin** [comment]
主进程只能是typescript

**Comment by yangjiaqiao** [comment]
> 主进程只能是typescript

好的，谢谢！！！！请问一下，打包配置，有没有详细的说明呢？
