### ISSUE TITLE
请问打包配置的路由模式，没有browser模式吗？

### ISSUE THREAD

**Issue by yangjiaqiao** [BySlin/umi-plugin-electron-builder#33]
![image](https://user-images.githubusercontent.com/51978469/116973994-f60adb80-acef-11eb-9829-627a1ef37820.png)

请问一下routerMode与Electron中mainWindow有什么关系呢？

**Comment by BySlin** [comment]
这个routeMode只在electron模式下生效，因为electron是从本地加载文件，使用browser打包后会白屏，加载不了。
非要用参考这个，把exportStatic打开，让umi把每个页面打包成单个html文件
![image](https://user-images.githubusercontent.com/16970823/116991230-d501b500-ad06-11eb-944b-4ddf37021fd3.png)

**Comment by yangjiaqiao** [comment]
> 这个routeMode只在electron模式下生效，因为electron是从本地加载文件，使用browser打包后会白屏，加载不了。
> 非要用参考这个，把exportStatic打开，让umi把每个页面打包成单个html文件
> ![image](https://user-images.githubusercontent.com/16970823/116991230-d501b500-ad06-11eb-944b-4ddf37021fd3.png)

请问一下，配置这个在开发环境下有效吗？还是必须是在打包安装的环境下有效呢？
![image](https://user-images.githubusercontent.com/51978469/117023109-6125d380-ad2b-11eb-8aa1-49adfff18a41.png)
请问是这样配置吗？

**Comment by yangjiaqiao** [comment]
> 这个routeMode只在electron模式下生效，因为electron是从本地加载文件，使用browser打包后会白屏，加载不了。
> 非要用参考这个，把exportStatic打开，让umi把每个页面打包成单个html文件
> ![image](https://user-images.githubusercontent.com/16970823/116991230-d501b500-ad06-11eb-944b-4ddf37021fd3.png)

![image](https://user-images.githubusercontent.com/51978469/117022359-c3ca9f80-ad2a-11eb-8eb3-9c908f8ac835.png)
请问是这样配置吗？

**Comment by BySlin** [comment]
只在打包后有效，不建议使用browser，electron下建议使用hash

**Comment by yangjiaqiao** [comment]
好的，谢谢！！！！！！！
