### ISSUE TITLE
怎样用vscode调试主进程？

### ISSUE THREAD

**Issue by cike8899** [BySlin/umi-plugin-electron-builder#34]
怎样用vscode调试主进程

**Comment by BySlin** [comment]
把插件更新到2.0.5，调试就默认打开
![image](https://user-images.githubusercontent.com/16970823/117536639-c1b85780-b02e-11eb-91f0-9af447af0806.png)
把vscode自动附加打开，直接运行electron:dev即可，找到调试左侧已载入脚本，找到webpack://main下要调试的脚本点开，如index.ts
![image](https://user-images.githubusercontent.com/16970823/117536691-1fe53a80-b02f-11eb-95f1-01af5e7b141b.png)
然后打断点即可，直接在编辑器打断点是不行的

**Comment by GreatAuk** [comment]
@BySlin v 2.1.4 怎么调试呢

**Comment by cike8899** [comment]
好像需要用powershell的terminal
