### ISSUE TITLE
请问在渲染进程怎么获取ipcRenderer

### ISSUE THREAD

**Issue by yangjiaqiao** [BySlin/umi-plugin-electron-builder#39]
请问在渲染进程怎么获取ipcRenderer呢？

**Comment by BySlin** [comment]
https://www.electronjs.org/docs/tutorial/context-isolation

在preload中注入api，然后页面可以直接使用

**Comment by yangjiaqiao** [comment]
找到了，谢谢

**Comment by GreatAuk** [comment]
新手。问下，是不建议直接在渲染进程是里引入 `electron` 的相关方法吗？按目前的配置（`contextIsolation: true`），如果在渲染进程引入 `electron` 的话，会报错
![image](https://user-images.githubusercontent.com/20253809/128993194-9123e998-7790-41c5-826c-ca7811e89c90.png)

但是我看官网的文档，都是直接在渲染进程中引入的
![image](https://user-images.githubusercontent.com/20253809/128993315-faf23f2e-0184-4115-a5ae-dfd07dacc4ad.png)
