### ISSUE TITLE
示例里面的main+renderer项目在electron:build:win打包时没有包含preload.js

### ISSUE THREAD

**Issue by zhang0ZGC** [BySlin/umi-plugin-electron-builder#42]
![企业微信截图_20210615143258](https://user-images.githubusercontent.com/10346399/122004609-32e5ea00-cde7-11eb-94df-6dcd01dcc136.png)

![企业微信截图_20210615143246](https://user-images.githubusercontent.com/10346399/122004613-337e8080-cde7-11eb-8a70-3c14e5b28773.png)

**Comment by BySlin** [comment]
![Dingtalk_20210615155440](https://user-images.githubusercontent.com/16970823/122014784-1602e400-cdf2-11eb-9922-6a1b53819353.jpg)
我这里没问题

**Comment by zhang0ZGC** [comment]
啊😰我本地再看看什么情况下出现的
