### ISSUE TITLE
开启 mfsu 或者 webpack5都会打包失败，报错mian.js找不到入口

### ISSUE THREAD

**Issue by zhangchuanbo** [BySlin/umi-plugin-electron-builder#43]
![image](https://user-images.githubusercontent.com/30680427/128319531-78a9a6f9-32eb-488d-ad14-4f62458cfebc.png)
已经配置extends为null还是报错
![image](https://user-images.githubusercontent.com/30680427/128319642-7c72c459-f734-4cc9-bf9f-4e5c0540d7cc.png)
是否可以默认在生产环境自动关闭，虽然我可以通过环境手动判断来开启或者关闭
或者有办法可以正确开启mfsu

**Comment by BySlin** [comment]
把buildType改成vite试试，

**Comment by xuhaichaoy** [comment]
遇到了一样的问题, 直接没有main.js 文件

**Comment by BySlin** [comment]
@zhangchuanbo @xuhaichaoy 新版本已修复

**Comment by xuhaichaoy** [comment]
@BySlin 

升级到2.1.4以后  electron:dev  以后  报Cannot read property 'Glob' of undefined

**Comment by xuhaichaoy** [comment]
@BySlin 

新版本还是不兼容 fastRefresh 嘛? 

报 Cannot read property 'Promise' of undefined

**Comment by BySlin** [comment]
@xuhaichaoy 新版本支持fastRefresh，我这边没有问题

**Comment by zhangchuanbo** [comment]
> @xuhaichaoy 新版本支持fastRefresh，我这边没有问题

我也没问题，但是我不敢开mfsu和webpack5。我将以前的umi2升上来，老项目改的electron，webpack打包的配置要改很多。
用ant-design-pro测了一下新版mfsu和webpack5打包是可以了。应该可以关闭这个问题了
