### ISSUE TITLE
第三方资源被打包进asar里面了

### ISSUE THREAD

**Issue by ElevenIjusee** [BySlin/umi-plugin-electron-builder#47]
我这边有引用第三方exe文件的需求，现在是放到public下但是会被一起打包到app.asar里面，想知道哪里可以配置忽略这个

**Comment by BySlin** [comment]
https://www.electron.build/configuration/contents.html#extraresources

**Comment by BySlin** [comment]
![image](https://user-images.githubusercontent.com/16970823/131671824-31a6d139-1a27-4e9e-a312-c20d4540f2d9.png)

**Comment by ElevenIjusee** [comment]
![Snipaste_2021-09-02_10-08-17](https://user-images.githubusercontent.com/34367672/131770441-e69d7c8b-7e8f-4ed0-9723-cd91dbc254da.png)
我在这里配置了，并且它也确实出现在了外面，但是asar文件的体积并没有减少，如果我把umi的public目录下这个几十m的文件夹删除，则asar体积会明显减少几十兆

**Comment by BySlin** [comment]
@ElevenIjusee 你把需要配置的目录放在public外就行，放在项目根目录下

**Comment by BySlin** [comment]
![image](https://user-images.githubusercontent.com/16970823/131849795-484f4add-ea05-4ef4-ae2c-a7b5b801fd80.png)

**Comment by ElevenIjusee** [comment]
![Snipaste_2021-09-03_10-02-39](https://user-images.githubusercontent.com/34367672/131940135-368267e2-bffa-4415-b0d6-24373c60589c.png)
![Snipaste_2021-09-03_10-03-27](https://user-images.githubusercontent.com/34367672/131940137-d910896d-487e-41bf-99d7-e62a0a1f8a01.png)
![Snipaste_2021-09-03_10-13-48](https://user-images.githubusercontent.com/34367672/131940262-e43a1fee-2893-4159-8344-9f69a44a0d62.png)
感谢，资源的问题已解决，但是打包这边好像还有问题。我尝试umi搭建了一个空白项目，么有改动任何设置，dev下正常运行但是win打包后无法找到index

**Comment by BySlin** [comment]
@ElevenIjusee mainWindow.loadURL('app://./index.html');  用这个加载，参考自动生成的代码，不要乱定义目录结构，你要自己定义目录结构就不建议用本插件

**Comment by BySlin** [comment]
![image](https://user-images.githubusercontent.com/16970823/131962873-528d6caa-7d5a-4fbe-a41e-6300ac35aae6.png)
