### ISSUE TITLE
请问进行打包成Linux安装包时报错

### ISSUE THREAD

**Issue by yangjiaqiao** [BySlin/umi-plugin-electron-builder#48]
![image](https://user-images.githubusercontent.com/51978469/133582530-d4952e59-2fab-48d9-8bac-2187e911f924.png)
打包的时候出现报错，请问这个是什么问题呢？

**Comment by BySlin** [comment]
你配置一下electron的镜像试试
yarn config set electron_mirror https://npm.taobao.org/mirrors/electron/
npm config set electron_mirror https://npm.taobao.org/mirrors/electron/

**Comment by yangjiaqiao** [comment]
> 你配置一下electron的镜像试试
> yarn config set electron_mirror https://npm.taobao.org/mirrors/electron/
> npm config set electron_mirror https://npm.taobao.org/mirrors/electron/

请问Electron是不是不能跨平台打包
