### ISSUE TITLE
请问在Electron打包时，发起请求后，出现在请求路径中增加app://前缀

### ISSUE THREAD

**Issue by yangjiaqiao** [BySlin/umi-plugin-electron-builder#49]
![38b855a918dbb88597a97abe9c791dd](https://user-images.githubusercontent.com/51978469/134451648-3bae1072-dbfd-409f-a90d-95da772d45a7.jpg)
会增加app://.前缀。这里使用微前端架构出现的问题

**Comment by BySlin** [comment]
你可以自定义协议，这个不是插件该解决的问题
