### ISSUE TITLE
可以去掉  log 时 Electron 的蓝框吗

### ISSUE THREAD

**Issue by arvinxx** [BySlin/umi-plugin-electron-builder#50]
如下图，这个蓝框非常影响调试体验…
![image](https://user-images.githubusercontent.com/28616219/134759282-1a80c1d5-abf5-4e6b-866f-96ea7a4a3d96.png)

看了下代码大概是这一行？

https://github.com/BySlin/umi-plugin-electron-builder/blob/main/src/compile/index.ts#L99

能否能给个配置项去掉这个日志

**Comment by BySlin** [comment]
已增加logProcess配置
```
    logProcess(log: string, type: LogType) {
      if (type === 'normal') {
        console.log(log);
      } else if (type === 'error') {
        console.error(log);
      }
    }
```
