### ISSUE TITLE
打包过程中，无法下载electron

### ISSUE THREAD

**Issue by HeWenKe** [BySlin/umi-plugin-electron-builder#57]
项目执行这个 yarn electron:build:win   后面报错
![image](https://user-images.githubusercontent.com/12146992/152764133-b8ad0771-869a-49aa-b7ea-31ae246250ff.png)

这个地址 ：https://npm.taobao.org/mirrors/electron/17.0.0/electron-v17.0.0-win32-x64.zip 不存在这个资源，17.0.0这个前面少个v,
正确的地址是https://npm.taobao.org/mirrors/electron/v17.0.0/electron-v17.0.0-win32-x64.zip  这怎么处理呢

**Comment by BySlin** [comment]
建议使用华为镜像
yarn config set electron_mirror https://mirrors.huaweicloud.com/electron/

**Comment by HeWenKe** [comment]
可以了，谢谢大佬
