### ISSUE TITLE
cannot unpack electron zip file, will be re-downloaded  error=zip: not a valid zip file

### ISSUE THREAD

**Issue by pxim** [BySlin/umi-plugin-electron-builder#58]
![image](https://user-images.githubusercontent.com/5111701/158092453-772ee344-3621-429e-bc67-3da2214547c0.png)

package.json
![image](https://user-images.githubusercontent.com/5111701/158092496-e49a2a3f-55ec-40f2-bc70-7b35956f471e.png)

**Comment by BySlin** [comment]
用华为镜像试试
yarn config set electron_mirror https://mirrors.huaweicloud.com/electron/

**Comment by pxim** [comment]
> 用华为镜像试试 yarn config set electron_mirror https://mirrors.huaweicloud.com/electron/

![image](https://user-images.githubusercontent.com/5111701/158094788-1a83dd90-34be-43ed-a72f-6d82c73f868a.png)
![image](https://user-images.githubusercontent.com/5111701/158094812-3610866d-5828-4012-a282-ebd90663a86b.png)
还是不行，我用浏览器点击 https://npm.taobao.org/mirrors/electron/17.1.2/electron-v17.1.2-win32-x64.zip 这个链接是可以下载的

我用了这个命令，为什么 运行 electron:build:win，还是下载的淘宝链接

**Comment by pxim** [comment]
我手动下载下来这个electron包，放到对应的目录下可以么？
就是我目前不知道把这个 electron.zip 放在哪里

**Comment by BySlin** [comment]
@pxim C:\Users\用户目录\AppData\Local\electron\Cache

**Comment by pxim** [comment]
> @pxim C:\Users\用户目录\AppData\Local\electron\Cache

![image](https://user-images.githubusercontent.com/5111701/158095821-db77083c-dbc6-4472-83e5-9bab4a23f64c.png)

这个目录下，有这个zip文件，不知道为什么还有  ⨯ zip: not a valid zip file 这个错误

**Comment by BySlin** [comment]
@pxim 你看这个压缩包你能手动解压不，看是不是压缩包损坏

**Comment by pxim** [comment]
> @pxim 你看这个压缩包你能手动解压不，看是不是压缩包损坏

确实是损坏了，解压不了，我替换了，现在可以build通过了，谢谢
![image](https://user-images.githubusercontent.com/5111701/158096293-da697b05-512c-4add-960b-455d91336d7b.png)
