### ISSUE TITLE
Fetch API cannot load app://./assets/envmap.hdr. URL scheme "app" is not supported.

### ISSUE THREAD

**Issue by pxim** [BySlin/umi-plugin-electron-builder#59]
![image](https://user-images.githubusercontent.com/5111701/158098980-2761ad40-7e27-459c-866a-fb96593b30d1.png)

我加了 这句
 `
      extraResources: [
        // WEB_PLUGIN_WIN,
        './public',
      ],
`
还是会出这个问题

![image](https://user-images.githubusercontent.com/5111701/158098847-4a6fca56-e161-47eb-a79a-6c5c5bde649c.png)

**Comment by BySlin** [comment]
参考这个给umi-request设置prefix
  webSecurity设置为false
https://github.com/BySlin/umi-plugin-electron-builder/issues/24

**Comment by BySlin** [comment]
静态文件放public目录下

**Comment by pxim** [comment]
> 
我的静态资源，是放在public下的，代码里引用，也是用的静态资源的使用方式， 现在获取不到，

**Comment by pxim** [comment]
> 参考这个给umi-request设置prefix webSecurity设置为false #24

这个没有效果，现在的问题，应该是静态资源获取不到，
electron:dev 模式下，是可以正常运行的；
是不是打包aser导致的问题，如果不打包这个，应该怎么配置呢

**Comment by BySlin** [comment]
builderOptions: {
  asar: false
}

**Comment by pxim** [comment]
> asar

这个设了false，build后还是不行，不知道为什么

------

在原来的基础上，生产环境下，调用页面的路径改成这样，就正常了
```
  if (isDevelopment) {
    mainWindow.loadURL('http://localhost:3000');
  } else {
    createProtocol('app');
    // mainWindow.loadURL('app://./index.html');

    const _appUrl = path.join(__dirname, 'index.html');
    mainWindow.loadURL(_appUrl);
  }
```

**Comment by seamory** [comment]
Just add those codes before createWindow could fix this problem.
```javascript
protocol.registerSchemesAsPrivileged([
  { scheme: 'app', privileges: { secure: false, standard: true, supportFetchAPI: true, } }
])
```
