### ISSUE TITLE
Mac 上打包其他OS的安装包

### ISSUE THREAD

**Issue by BobReal0822** [BySlin/umi-plugin-electron-builder#6]
我在 Mac 上只能打包 Mac 的安装包，有没有办法同时打包 Windows 和 Linux 的安装包？

**Comment by BySlin** [comment]
更新版本后，你可以尝试一下

**Comment by BobReal0822** [comment]
很赞👍，感谢！

**Comment by BySlin** [comment]
builderOptions中的参数参考：https://www.electron.build/configuration/configuration
如配置图标
```
  electronBuilder: {
    builderOptions: {
      appId: 'com.test.test',
      productName: '测试',
      mac: {
        icon: 'icons/icon.icns',
      },
    },
  },
```
命令行参数参考：https://www.electron.build/cli
如打包32位
umi build electron --win --ia32
