### ISSUE TITLE
请问 在vscode里怎么debug main.js里的代码？

### ISSUE THREAD

**Issue by pxim** [BySlin/umi-plugin-electron-builder#60]
我参考了 
https://www.electronjs.org/zh/docs/latest/tutorial/debugging-vscode
这个，添加了 launch.json，
在main.js里添加了断点，
然后启动 npm run electron:dev

发现没有效果

**Comment by BySlin** [comment]
https://github.com/BySlin/umi-plugin-electron-builder/blob/main/examples/demo/.vscode/launch.json

**Comment by BySlin** [comment]
![image](https://user-images.githubusercontent.com/16970823/159118077-e9182037-3a59-41f9-816c-7c1f818dd596.png)

**Comment by pxim** [comment]
> 

我launch.json按照链接里的改了

然后你这个图里 debug electron进程的，我想知道 在package.json里具体命令是什么呢

用  "electron:dev": "umi dev electron", 这个命令的话，还是不行

**Comment by BySlin** [comment]
https://github.com/BySlin/umi-plugin-electron-builder/tree/main/examples/demo 
参考示例

**Comment by pxim** [comment]
> https://github.com/BySlin/umi-plugin-electron-builder/tree/main/examples/demo 参考示例

![image](https://user-images.githubusercontent.com/5111701/159156256-f5040290-0d5c-48b8-89bb-b1416b9bead3.png)

用了这个example，没有debug效果

**Comment by pxim** [comment]
可以了，需要管理员权限，运行vscode，然后在
![image](https://user-images.githubusercontent.com/5111701/159156629-6691f407-2c5b-4d6b-86c1-6e465b4d3a85.png)

谢谢了
