### ISSUE TITLE
执行umi electron init后终端没有任何反应，没有报错就自动结束任务了

### ISSUE THREAD

**Issue by ElevenIjusee** [BySlin/umi-plugin-electron-builder#62]
期间也没有任何弹窗，系统是win11

**Comment by BySlin** [comment]
执行 yarn electron:init
没用的话用cmd试试，我这边在win11下没问题
还不行把https://github.com/BySlin/umi-plugin-electron-builder/tree/main/template下的目录及文件手动复制到src目录，
执行yarn add electron electron-builder --dev
