### ISSUE TITLE
electron打包无限嵌套

### ISSUE THREAD

**Issue by minzhang2** [BySlin/umi-plugin-electron-builder#65]
<img width="621" alt="image" src="https://user-images.githubusercontent.com/15793061/181691463-3bf512fc-38ae-4e4b-ab35-2da650759fb1.png">
version:2.x最新版本
使用main+renderer双目录，public放在renderer下面

**Comment by BySlin** [comment]
https://github.com/BySlin/umi-plugin-electron-builder/tree/2.x/examples/main%2Brenderer
这个demo有这个问题吗，我没有mac，我在windows测试上是正常的

**Comment by minzhang2** [comment]
不用public目录是ok的，加了编译出现异常

**Comment by minzhang2** [comment]
参考下如下报错
Error: ENAMETOOLONG: name too long, copyfile '/Users/xxx/work/code/akey-im-desk/dist_electron/mac-arm64/xxx.app/Contents/Resources/dist_electron/mac-arm64/xxx.app/Contents/Resources/dist_electron/mac-arm64/xxx.app/Contents/Resources/dist_electron/mac-arm64/xxx.app/Contents/Resources/dist_electron/mac-arm64/xxx.app/Contents/Resources/dist_electron/mac-arm64/xxx.app/Contents/Resources/dist_electron/mac-arm64/xxx.app/Contents/Resources/dist_electron/mac-arm64/xxx.app/Contents/Resources/dist_electron/mac-arm64/xxx.app/Contents/Resources/dist_electron/mac-arm64/xxx.app/Contents/Resources/dist_electron/mac-arm64/xxx.app/Contents/Resources/dist_electron/mac-arm64/xxx.app/Contents/Resources/dist_electron/mac-arm64/xxx.app/Contents/Resources/node_modules/.cache/terser-webpack-plugin/content-v2/sha512/93/50/d1272a4d7a5c0d6625390cd875c55ec6042188c4fce0c7641d3d38d7e7a8bb66b18d67cc7f4d3a86df55cfb1e196b890752ef939981b6828791c7447d2f6' -> '/Users/xxx/work/code/akey-im-desk/dist_electron/mac-arm64/xxx.app/Contents/Resources/dist_electron/mac-arm64/xxx.app/Contents/Resources/dist_electron/mac-arm64/xxx.app/Contents/Resources/dist_electron/mac-arm64/xxx.app/Contents/Resources/dist_electron/mac-arm64/xxx.app/Contents/Resources/dist_electron/mac-arm64/xxx.app/Contents/Resources/dist_electron/mac-arm64/xxx.app/Contents/Resources/dist_electron/mac-arm64/xxx.app/Contents/Resources/dist_electron/mac-arm64/xxx.app/Contents/Resources/dist_electron/mac-arm64/xxx.app/Contents/Resources/dist_electron/mac-arm64/xxx.app/Contents/Resources/dist_electron/mac-arm64/xxx.app/Contents/Resources/dist_electron/mac-arm64/xxx.app/Contents/Resources/dist_electron/mac-arm64/xxx.app/Contents/Resources/node_modules/.cache/terser-webpack-plugin/content-v2/sha512/93/50/d1272a4d7a5c0d6625390cd875c55ec6042188c4fce0c7641d3d38d7e7a8bb66b18d67cc7f4d3a86df55cfb1e196b890752ef939981b6828791c7447d2f6'
    at processImmediate (node:internal/timers:466:21)
From previous event:
    at walk (/Users/xxx/work/code/akey-im-desk/node_modules/builder-util/src/fs.ts:77:51)
    at /Users/xxx/work/code/akey-im-desk/node_modules/app-builder-lib/src/fileMatcher.ts:351:12
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
