### ISSUE TITLE
umi4下使用pnpm electron:init 一直出问题，有yarn方法么？

### ISSUE THREAD

**Issue by pxim** [BySlin/umi-plugin-electron-builder#68]
umi4下使用pnpm postinstall 一直出问题
![image](https://user-images.githubusercontent.com/5111701/202651619-5524f8d9-b270-4fd4-879d-bf2e0d771520.png)

然后执行 yarn run postinstall 也会报错
![image](https://user-images.githubusercontent.com/5111701/202652201-1abd642c-b965-4f9d-9274-b4f7d317f55b.png)

**Comment by BySlin** [comment]
把pnpm改成yarn就行

**Comment by pxim** [comment]
> 把pnpm改成yarn就行

加了这句 plugins: [require.resolve("umi-plugin-electron-builder")]，运行 yarn postinstall，就会报错，不加就正常
![image](https://user-images.githubusercontent.com/5111701/202654191-41f0508c-65b7-4fab-8253-9d06534cf237.png)

**Comment by BySlin** [comment]
node_modules删了重新yarn

**Comment by pxim** [comment]
> node_modules删了重新yarn

试了，还是会这样，我甚至全部删了，重新 yarn create umi，然后再安装这个插件，到这一步，会出同样的问题，是不是这行配置有问题，在最新的 umi脚手架版本里

**Comment by BySlin** [comment]
你得第一张图是文件被占用了，无法删除，第二张不知道是什么，我这边用的也是yarn是没有问题的
