### ISSUE TITLE
umi4 配置项.umirc 不兼容umi插件配置项

### ISSUE THREAD

**Issue by vanness30214** [BySlin/umi-plugin-electron-builder#69]
不兼容umi其他配置项

qiankun: {
    master: {},
  }
加个乾坤配置项就报错无法运行

**Comment by BySlin** [comment]
你确定是因为这个插件吗？，加配置项报错应该是对应插件没有加载

**Comment by vanness30214** [comment]
他会报qiankun是非法配置，但如果我在纯umi/max插件里面是不会有此情况

**Comment by BySlin** [comment]
我试了一下，我这边没有问题
![image](https://user-images.githubusercontent.com/16970823/206667948-09a74d36-cf13-4f7d-b0df-9178949026bf.png)

**Comment by BySlin** [comment]
使用@umijs/max的话，将脚本中的umi改成max
![image](https://user-images.githubusercontent.com/16970823/206668199-5073d773-1f60-4b14-9f40-f50d1488d02e.png)
