### ISSUE TITLE
打包报错 :require() of ES Module

### ISSUE THREAD

**Issue by LuciferWZX** [BySlin/umi-plugin-electron-builder#70]
![image](https://user-images.githubusercontent.com/33945463/206680494-3d5518ea-b283-4aeb-b606-1f83095c2516.png)
我这边有用import和require
![image](https://user-images.githubusercontent.com/33945463/206680803-9e8e8db4-9b53-4c4c-9e85-432ca3a531e1.png)
整个package.json是这样的
![image](https://user-images.githubusercontent.com/33945463/206680937-b69ad295-bade-4a53-b418-3d787d8f18d5.png)
.umiirc.ts是这样的
![image](https://user-images.githubusercontent.com/33945463/206681090-903c0d05-05e2-4fb6-9a79-8540d1e949fd.png)
求助这边到底是哪里有问题的

**Comment by BySlin** [comment]
把buildType配置为webpack试试

**Comment by LuciferWZX** [comment]
> 把buildType配置为webpack试试

我试一下

**Comment by LuciferWZX** [comment]
> 

不行，还是报错
![image](https://user-images.githubusercontent.com/33945463/206682663-2ec85b10-26e2-4a81-88d0-4658a16af3d8.png)

**Comment by LuciferWZX** [comment]
> 

vite也试过了，也不行

**Comment by BySlin** [comment]
这个包好像有d.ts 把@types/pouchdb装一下，用import方式导包试试

**Comment by BySlin** [comment]
你这个报错是因为这个包现在是es版本的，现在umi支持的还是commonjs，commonjs不能直接引用es module，用require的方式导包不会编译

**Comment by BySlin** [comment]
现在nodejs原生支持了import xxx form 'xxx';这种语法，但是这种语法不能和require混用，require和import只能2选一

**Comment by BySlin** [comment]
> > 
> 
> vite也试过了，也不行

我看了一下你那个项目，你把pouchdb-find也加入externals就行了，buildType默认vite就行
