### ISSUE TITLE
大神有交流群或帮助文档吗，完全懵逼状态

### ISSUE THREAD

**Issue by junegod** [BySlin/umi-plugin-electron-builder#74]
我现在有个前端项目umi+ antdv5pro 的，我想打包一个桌面端，
是单独一个electron项目，远程加载mainWindow.loadFile('https://abc.com') 
还是集成electron到自己项目里，每次有改动就打包，加载本地文件mainWindow.loadFile('build/index.html') 
两种方式开发上有什么区别；
还有你说的那个混合项目模式和main+renderer项目结构 是什么意思

**Comment by BySlin** [comment]
第一个问题 你觉得怎么方便就怎么用
第二个问题 混合项目就是主进程代码和渲染进程代码在一个目录下，项目结构简单
main+renderer项目结构，就是主进程的代码和渲染进程的代码分开在不同的目录，这样的项目结构有些人认为好维护一点
这两种模式就项目结构的区别，实际开发没有区别，打包也没有区别，对electron不是很熟的用混合项目就行了

此项目只是一个umijs的打包插件而已，至于electron怎么用你得自己学了

**Comment by junegod** [comment]
加载远程文件就比较方便更新，不用更新应用。但是开发起来两种没有区别么

**Comment by BySlin** [comment]
如果你仅仅就是网页套壳那没什么区别。

**Comment by junegod** [comment]
3q
