### ISSUE TITLE
关于资源路径的引用

### ISSUE THREAD

**Issue by LuciferWZX** [BySlin/umi-plugin-electron-builder#76]
<img width="1222" alt="image" src="https://github.com/BySlin/umi-plugin-electron-builder/assets/33945463/68d74a47-f5bd-4ef3-b061-25df7f95d390">
我这边想引用public里面的

<img width="875" alt="image" src="https://github.com/BySlin/umi-plugin-electron-builder/assets/33945463/5d025e79-d524-4991-ad59-bcf9a683eaec">
是这个位置 /Users/wuzhixin/Desktop/workspace/wll_system/src/.umi/electron
该怎么设置正确的文件路径，或者说有没有一个变量 const sourcePath = process.env.public ，开发和打包后都可以得到正确的资源呢

**Comment by BySlin** [comment]
```typescript
export const STATIC_PATH: string = path.join(
  isDevelopment ? path.join(process.cwd(), 'public') : process.resourcesPath,
);
```

**Comment by LuciferWZX** [comment]
> ```ts
> export const STATIC_PATH: string = path.join(
>   isDevelopment ? path.join(process.cwd(), 'public') : process.resourcesPath,
> );
> ```

是可行的，谢谢啦
