### ISSUE TITLE
mac 环境下 运行 build的时候报错 Path is a directory: rm returned EISDIR (is a directory)

### ISSUE THREAD

**Issue by hyyqcweb** [BySlin/umi-plugin-electron-builder#77]
<img width="1049" alt="image" src="https://github.com/BySlin/umi-plugin-electron-builder/assets/17583072/e2a2c8d0-6819-40e9-adf6-9edd616d8a3d">

## package.json
<img width="704" alt="image" src="https://github.com/BySlin/umi-plugin-electron-builder/assets/17583072/ffa6780b-38ae-44ba-a7aa-8a607c554417">

**Comment by hyyqcweb** [comment]
@BySlin postinstall，init，dev 均未见报错，但是 dev 环境那个 自动打开的 Electron 软件好像是点不开的，build 前面都是好的，就到了后面是这个报错，我也查了 [electron-builder issues](https://github.com/electron-userland/electron-builder/pull/5961/commits/1691198b3e0263e196c3b78e3f44dfd6d2b0c032)，但是不知道在我们插件中是在哪儿改

**Comment by hyyqcweb** [comment]
另外：pnpm electron:build:mac 或者是 yarn electron:build:mac 都试过，都是报的这个错误，生成不了 dmg安装包

**Comment by BySlin** [comment]
你用本项目examples下demo项目试试

**Comment by hyyqcweb** [comment]
@BySlin 好的，大佬，我试试

**Comment by hyyqcweb** [comment]
<img width="894" alt="image" src="https://github.com/BySlin/umi-plugin-electron-builder/assets/17583072/27635033-c0de-4c19-a4b1-3ba3a18b8308">
demo build 最后也是报错了 @BySlin

**Comment by BySlin** [comment]
> <img alt="image" width="894" src="https://user-images.githubusercontent.com/17583072/244607149-27635033-c0de-4c19-a4b1-3ba3a18b8308.png"> demo build 最后也是报错了 @BySlin

这个报错是electron没有正确安装

**Comment by hyyqcweb** [comment]
> > <img alt="图像" width="894" src="https://user-images.githubusercontent.com/17583072/244607149-27635033-c0de-4c19-a4b1-3ba3a18b8308.png">demo build 最后也是报错了@BySlin
> 
> 这个报错是electron没有正确安装

那我应该如何操作呢。

**Comment by BySlin** [comment]
> > > <img alt="图像" width="894" src="https://user-images.githubusercontent.com/17583072/244607149-27635033-c0de-4c19-a4b1-3ba3a18b8308.png">demo build 最后也是报错了@BySlin
> > 
> > 
> > 这个报错是electron没有正确安装
> 
> 那我应该如何操作呢。

用yarn试试，把.umirc.ts中的npmClient也改成yarn，删除node_modules目录，在yarn更新依赖

**Comment by hyyqcweb** [comment]
> > > > <img alt="图像" width="894" src="https://user-images.githubusercontent.com/17583072/244607149-27635033-c0de-4c19-a4b1-3ba3a18b8308.png">demo build 最后也是报错了@BySlin
> > > 
> > > 
> > > 这个报错是electron没有正确安装
> > 
> > 
> > 那我应该如何操作呢。
> 
> 用yarn试试，把.umirc.ts中的npmClient也改成yarn，删除node_modules目录，在yarn更新依赖

好的，我现在试一下

**Comment by hyyqcweb** [comment]
> > > > > <img alt="图像" width="894" src="https://user-images.githubusercontent.com/17583072/244607149-27635033-c0de-4c19-a4b1-3ba3a18b8308.png">demo build 最后也是报错了@BySlin
> > > > 
> > > > 
> > > > 这个报错是electron没有正确安装
> > > 
> > > 
> > > 那我应该如何操作呢。
> > 
> > 
> > 用yarn试试，把.umirc.ts中的npmClient也改成yarn，删除node_modules目录，在yarn更新依赖
> 
> 好的，我现在试一下

<img width="414" alt="image" src="https://github.com/BySlin/umi-plugin-electron-builder/assets/17583072/62fab7b9-aaff-4d93-9fa8-0cb8f30181b6">
<img width="900" alt="image" src="https://github.com/BySlin/umi-plugin-electron-builder/assets/17583072/d6fc159f-22fa-4370-9bca-afb53a065b92">
这个看起来是好的，但我自己的项目这个报错是为什么呢

**Comment by BySlin** [comment]
更新插件版本和electron-builder的版本试试 @hyyqcweb

**Comment by hyyqcweb** [comment]
> electron-builder

好的，我试试

**Comment by hyyqcweb** [comment]
@BySlin pnpm 换成了 yarn，在安装依赖的时候就出错了，是网络问题ma
<img width="1030" alt="image" src="https://github.com/BySlin/umi-plugin-electron-builder/assets/17583072/efd6dc0b-8ae4-479f-a299-361590e9a72a">

**Comment by hyyqcweb** [comment]
@BySlin umi setup 环节就有问题了，这个两个版本的话，排查方向是啥，大佬

**Comment by BySlin** [comment]
> @BySlin umi setup 环节就有问题了，这个两个版本的话，排查方向是啥，大佬

你这个好像是配置文件的参数有问题

**Comment by hyyqcweb** [comment]
> > @BySlin umi setup 环节就有问题了，这个两个版本的话，排查方向是啥，大佬
> 
> 你这个好像是配置文件的参数有问题

<img width="779" alt="image" src="https://github.com/BySlin/umi-plugin-electron-builder/assets/17583072/366b72f5-cd87-4419-a6b7-9879705c0108">
<img width="801" alt="image" src="https://github.com/BySlin/umi-plugin-electron-builder/assets/17583072/877f8b93-9106-4f73-a809-68c03ee5fdd3">

**Comment by hyyqcweb** [comment]
我试了 yarn 和 pnpm 安装，并且切换了 npmClient 都是报错的，同样的错
<img width="799" alt="image" src="https://github.com/BySlin/umi-plugin-electron-builder/assets/17583072/84081f55-1b8d-414b-b7f0-bfa8cd2a2a81">

**Comment by BySlin** [comment]
@hyyqcweb 你只配用到的配置就行了，不用的删了就行

**Comment by hyyqcweb** [comment]
> @hyyqcweb 你只配用到的配置就行了，不用的删了就行

那我删了 electronBuilder 这个配置，我再试试

**Comment by hyyqcweb** [comment]
<img width="699" alt="image" src="https://github.com/BySlin/umi-plugin-electron-builder/assets/17583072/f509866f-77c9-4671-9dbf-563d5f002bba">
删了 electronBuilder，报错不一样了

**Comment by hyyqcweb** [comment]
呃，好像还是一样。。。

**Comment by hyyqcweb** [comment]
@BySlin 剩下的配置信息
<img width="629" alt="image" src="https://github.com/BySlin/umi-plugin-electron-builder/assets/17583072/b37049fa-da5e-49d6-be8c-beb159af6938">

**Comment by BySlin** [comment]
@hyyqcweb @umijs/max也要更新版本，这个报错是插件新版本基于umijs新的校验插件，老版本不支持这个校验插件所有undefined

**Comment by hyyqcweb** [comment]
> umijs/max

更新到最新版本吗

**Comment by BySlin** [comment]
至少也是demo里的那个版本

**Comment by hyyqcweb** [comment]
> 至少也是demo里的那个版本

ok, demo 里面是 67，我更新到 70

**Comment by hyyqcweb** [comment]
@BySlin 感谢大佬，真的是版本的问题。。。哎，搞了一上午没搞定

**Comment by hyyqcweb** [comment]
@BySlin 打出来的资源引用好像有问题。。。。

**Comment by hyyqcweb** [comment]
引用在线的一个网址地址是显示不出来的吗？ 比如 //baidu.com/1.jpg

**Comment by BySlin** [comment]
可能是跨域问题

**Comment by hyyqcweb** [comment]
但是 dev 好像是好的

**Comment by BySlin** [comment]
dev是通过http访问的，打包之后通过file://访问的

**Comment by hyyqcweb** [comment]
> dev是通过http访问的，打包之后通过file://访问的

就是网络图片，静态资源比如项目中引入的图片，我看了 pro 环境是好的

**Comment by BySlin** [comment]
//baidu.com/1.jpg这样的地址是基于当前用什么协议访问的 打包后是file://
http://baidu.com/1.jpg这样的地址是正常的

**Comment by hyyqcweb** [comment]
哦哦，原来如此，我在试试，我们为了不区别 https 和 http，直接就写了 //www.baidu.com 类似于这样的

**Comment by hyyqcweb** [comment]
@BySlin 大佬，我在问一个问题，他打开软件的时候，首次是 404，是需要什么配置吗
<img width="800" alt="image" src="https://github.com/BySlin/umi-plugin-electron-builder/assets/17583072/4560cfda-0441-43da-8464-c92a24f0e5d2">

**Comment by hyyqcweb** [comment]
<img width="966" alt="image" src="https://github.com/BySlin/umi-plugin-electron-builder/assets/17583072/c50dd5e2-899b-4ee9-bef2-57c72ae71752">

**Comment by hyyqcweb** [comment]
是 hash 路由的关系，我看有个#号 ？

**Comment by BySlin** [comment]
如果你web不是hash路由的话，那应该是跟路由有关系，electron下使用不了browser路由

**Comment by hyyqcweb** [comment]
> 不是hash路由的话，那应该是跟路由有关系，e

嗯，我看了一下 web 默认是 browser，然后 electron 打出来的没有 browser，只有 hash 和 memory，只能用 hash，但是 hash 好像刷新一下又回到首页了
