### ISSUE TITLE
dev报错

### ISSUE THREAD

**Issue by disturbwe** [BySlin/umi-plugin-electron-builder#8]
![image](https://user-images.githubusercontent.com/36886269/96709680-9d1bcb80-13cd-11eb-91a1-85dffeca1ae3.png)

**Comment by disturbwe** [comment]
![Uploading image.png…]()

**Comment by BySlin** [comment]
把main.ts中installExtension注释，这是因为你连不上谷歌浏览器的插件商店

**Comment by disturbwe** [comment]
解决了，谢谢大佬
