### ISSUE TITLE
能否优化下目录结构？

### ISSUE THREAD

**Issue by arvinxx** [BySlin/umi-plugin-electron-builder#9]
例如现在是将 main 和其他模块拉平目录架构的，一旦业务稍微复杂点，就会变成这样：
```
src
├── common
├── global.less
├── hooks
├── main
├── pages
├── theme
├── tsconfig.json
└── utils
```
上面这样一搞，就完全不知道哪些是electron 的，哪些是浏览器的，哪些是公用的，就很容易导致认知上的偏差。

electron 里会把浏览器端叫做 renderer，pages等页面应该要放到 renderer 里面去，这样架构上才会比较合理，就像下面这样：

```
src
├── common
│   └── utils
├── main
│   ├── main.ts
│   └── tsconfig.json
└── renderer
    ├── global.less
    ├── hooks
    ├── pages
    ├── theme
    ├── tsconfig.json
    └── utils

```
能不能在插件层面做下目录架构上的优化？在简单场景下支持现在的方案，在复杂场景下支持我提的下面这种方案。

**Comment by BySlin** [comment]
参考 https://github.com/BySlin/umi-plugin-electron-builder/tree/master/examples/main%2Brenderer

**Comment by arvinxx** [comment]
我的案例见上分支 
https://github.com/arvinxx/umi-electron-template/commit/dcdb60359891f5ef665f3bd584dd6a689a5777c4

存在的问题主要表现为在 ts 类型报错。 感觉是 `mainWebpackConfig` 没有读取到？

![image](https://user-images.githubusercontent.com/28616219/108389098-4ecaec00-724a-11eb-9723-9bb605c648b4.png)

----------

失败案例说明：
master 分支是我之前采用的伪双目录结构，能够正常 dev 和 build ，但是比较 不方便。
我在 beta/update-plugin 分支中按照上述案例调整了配置项，但是并没有正常跑通。

**Comment by arvinxx** [comment]
另外可以看到，之前 config 文件夹在根目录下，而现在双目录结构后，config 却跑到了 `renderer` 底下。但是 config 在功能上既包含了 `renderer` 的配置项，也包含 `main` 的配置项。

所以合理的情况应该还是在根目录配置 `config/config.ts` 或 `.umirc.ts` 。

**Comment by BySlin** [comment]
@arvinxx 
第一个问题
你没有设置APP_ROOT 
![image](https://user-images.githubusercontent.com/16970823/108394710-f7c81580-724f-11eb-8bba-e27ce376cc41.png)
第一个问题
建议在根目录config配置config.ts，再import到renderer下的.umirc.ts，设置APP_ROOT后.umirc.ts必须在APP_ROOT下
![image](https://user-images.githubusercontent.com/16970823/108395417-b71ccc00-7250-11eb-94bb-5ef48e34cac8.png)
![image](https://user-images.githubusercontent.com/16970823/108395477-c7cd4200-7250-11eb-8f01-47df3212a2cc.png)

**Comment by arvinxx** [comment]
emm.... 我在本地新建了.env 加了APP_ROOT，好像忘记commit了。写在scripts里太啰嗦了。 我加了之后是有那个错误的

**Comment by BySlin** [comment]
@arvinxx APP_ROOT只能设置在scripts里面，设置在.env是无效的

**Comment by arvinxx** [comment]
第二个问题如果可以这样解决的话，是不是也可以在插件层面封装掉？

**Comment by arvinxx** [comment]
> @arvinxx APP_ROOT只能设置在scripts里面，设置在.env是无效的

这样啊 那我再试下

**Comment by arvinxx** [comment]
已可用。

一个优化建议：新开一个 issue：#15
